# Generated by Django 5.1.6 on 2025-03-09 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterconsumemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_consume', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AnamnesisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('medical_conditions', models.JSONField(default=list)),
                ('medications', models.JSONField(default=list)),
                ('exercise_frequency', models.CharField(max_length=255)),
                ('goals', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
