# Generated by Django 5.1.6 on 2025-03-09 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_bloodpressuremodel_glycemiamodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glycemia_pre_workout', models.IntegerField()),
                ('glycemia_post_workout', models.IntegerField()),
                ('blood_pressure_pre_workout_systolic', models.IntegerField()),
                ('blood_pressure_pre_workout_diastolic', models.IntegerField()),
                ('blood_pressure_post_workout_systolic', models.IntegerField()),
                ('blood_pressure_post_workout_diastolic', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
