# Generated by Django 5.1.6 on 2025-03-09 20:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_dailyrecordmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecordmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bloodpressuremodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='glycemiamodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
