# Generated by Django 5.1.6 on 2025-03-09 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_dailyrecordmodel_date_alter_bloodpressuremodel_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecordmodel',
            name='blood_pressure_post_workout_diastolic',
        ),
        migrations.RemoveField(
            model_name='dailyrecordmodel',
            name='blood_pressure_post_workout_systolic',
        ),
        migrations.RemoveField(
            model_name='dailyrecordmodel',
            name='blood_pressure_pre_workout_diastolic',
        ),
        migrations.RemoveField(
            model_name='dailyrecordmodel',
            name='blood_pressure_pre_workout_systolic',
        ),
        migrations.RemoveField(
            model_name='dailyrecordmodel',
            name='glycemia_post_workout',
        ),
        migrations.RemoveField(
            model_name='dailyrecordmodel',
            name='glycemia_pre_workout',
        ),
        migrations.AddField(
            model_name='dailyrecordmodel',
            name='blood_pressure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.bloodpressuremodel'),
        ),
        migrations.AddField(
            model_name='dailyrecordmodel',
            name='glycemia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.glycemiamodel'),
        ),
    ]
