# Generated by Django 5.1.6 on 2025-03-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
